### ISSUE TITLE
($listName) must be of type string, null given

### ISSUE THREAD

**Issue by websmyth** [statamic-rad-pack/mailchimp#128]
### Description

Forms with Mailchimp configuration are generating this error:

```
[2024-09-04 11:06:03] production.ERROR: StatamicRadPack\Mailchimp\NewsletterDriver::subscribeOrUpdate(): Argument #3 ($listName) must be of type string, null given, called in /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 357 {"userId":"729cd96b-0a79-4710-b02b-c56f27cd3b29","exception":"[object] (TypeError(code: 0): StatamicRadPack\\Mailchimp\\NewsletterDriver::subscribeOrUpdate(): Argument #3 ($listName) must be of type string, null given, called in /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 357 at /home/ploi/[redacted]/vendor/statamic-rad-pack/mailchimp/src/NewsletterDriver.php:59)
[stacktrace]
#0 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(357): StatamicRadPack\\Mailchimp\\NewsletterDriver->subscribeOrUpdate()
#1 /home/ploi/[redacted]/vendor/statamic-rad-pack/mailchimp/src/Subscriber.php(131): Illuminate\\Support\\Facades\\Facade::__callStatic()
#2 /home/ploi/[redacted]/vendor/statamic-rad-pack/mailchimp/src/Listeners/AddFromSubmission.php(12): StatamicRadPack\\Mailchimp\\Subscriber->subscribe()
#3 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): StatamicRadPack\\Mailchimp\\Listeners\\AddFromSubmission->handle()
#4 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#5 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#6 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(458): Illuminate\\Events\\Dispatcher->dispatch()
#7 /home/ploi/[redacted]/vendor/statamic/cms/src/Events/Event.php(21): event()
#8 /home/ploi/[redacted]/vendor/statamic/cms/src/Forms/Submission.php(181): Statamic\\Events\\Event::dispatch()
#9 /home/ploi/[redacted]/vendor/statamic/cms/src/Http/Controllers/FormController.php(78): Statamic\\Forms\\Submission->save()
#10 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\FormController->submit()
#11 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#12 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#13 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/Route.php(208): Illuminate\\Routing\\Route->runController()
#14 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#15 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#16 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#18 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#20 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#22 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#24 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#25 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#27 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#29 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/HandlePrecognitiveRequests.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\HandlePrecognitiveRequests->handle()
#31 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#33 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#34 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#35 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#36 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#37 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#38 /home/ploi/[redacted]/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#40 /home/ploi/[redacted]/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle()
#42 /home/ploi/[redacted]/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#44 /home/ploi/[redacted]/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#46 /home/ploi/[redacted]/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#48 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#51 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#54 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#56 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#58 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#60 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#62 /home/ploi/[redacted]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#63 /home/ploi/[redacted]/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#64 {main}
"} 
```

### Steps to reproduce

Example form:

```
mailchimp:
  enabled: true
  settings:
    audience_id: 4868b61ce2
    tag: Momentum
    interests_field: null
    disable_opt_in: false
    check_consent: false
    consent_field: null
    merge_fields:
      -
        field_name: name
        tag: FNAME
title: 'Guide: Marketing Momentum'
honeypot: extra_q
```

### Environment

Environment
Application Name: [redacted]
Laravel Version: 11.22.0
PHP Version: 8.2.23
Composer Version: 2.7.8
Environment: production
Debug Mode: OFF
URL: [redacted]
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.24.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.12.1
jaygeorge/statamic-vanilla-peak-seo: dev-main
spatie/statamic-responsive-images: 5.0.0
statamic-rad-pack/mailchimp: 5.1.2
withcandour/aardvark-seo: 5.0.0

**Comment by ryanmitchell** [comment]
Sorry - this should fix it https://github.com/statamic-rad-pack/mailchimp/pull/129

**Comment by websmyth** [comment]
Thanks for looking at that so quickly – that’s done it!
